-- MySQL Script generated by MySQL Workbench
-- Thu Jun 29 08:51:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asscic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asscic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asscic` DEFAULT CHARACTER SET utf8 ;
USE `asscic` ;

-- -----------------------------------------------------
-- Table `asscic`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(16) NULL,
  `direccion` VARCHAR(250) NULL,
  `telefono` INT(9) NULL,
  `correo` VARCHAR(50) NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`institucion` (
  `idinstitucion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`voluntario` (
  `idvoluntario` INT NOT NULL AUTO_INCREMENT,
  `carnet` VARCHAR(45) NULL,
  `fecha_ingreso` INT(11) NOT NULL,
  `fecha_ultima` INT(11) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  `institucion_idinstitucion` INT NOT NULL,
  `carrera_idcarrera` INT NOT NULL,
  `area_idarea` INT NOT NULL,
  PRIMARY KEY (`idvoluntario`, `persona_idpersona`, `institucion_idinstitucion`, `carrera_idcarrera`, `area_idarea`),
  UNIQUE INDEX `carnet_UNIQUE` (`carnet` ASC),
  INDEX `fk_voluntario_persona1_idx` (`persona_idpersona` ASC),
  INDEX `fk_voluntario_Universidad1_idx` (`institucion_idinstitucion` ASC),
  INDEX `fk_voluntario_carrera1_idx` (`carrera_idcarrera` ASC),
  INDEX `fk_voluntario_area1_idx` (`area_idarea` ASC),
  CONSTRAINT `fk_voluntario_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntario_Universidad1`
    FOREIGN KEY (`institucion_idinstitucion`)
    REFERENCES `asscic`.`institucion` (`idinstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntario_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `asscic`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntario_area1`
    FOREIGN KEY (`area_idarea`)
    REFERENCES `asscic`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`trabajador` (
  `idtrabajador` INT NOT NULL AUTO_INCREMENT,
  `carnet` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  `area_idarea` INT NOT NULL,
  PRIMARY KEY (`idtrabajador`, `persona_idpersona`, `area_idarea`),
  UNIQUE INDEX `carnet_UNIQUE` (`carnet` ASC),
  INDEX `fk_trabajador_persona1_idx` (`persona_idpersona` ASC),
  INDEX `fk_trabajador_area1_idx` (`area_idarea` ASC),
  CONSTRAINT `fk_trabajador_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajador_area1`
    FOREIGN KEY (`area_idarea`)
    REFERENCES `asscic`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`asistencia` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora_entrada` INT(11) NOT NULL,
  `hora_salida` INT(11) NOT NULL,
  `hora_acumulada` DOUBLE NULL,
  `idpersona` INT NOT NULL,
  PRIMARY KEY (`idasistencia`, `idpersona`),
  INDEX `fk_asistencia_persona1_idx` (`idpersona` ASC),
  CONSTRAINT `fk_asistencia_persona1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`actividades` (
  `idactividades` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `area_idarea` INT NOT NULL,
  PRIMARY KEY (`idactividades`, `area_idarea`),
  INDEX `fk_actividades_area1_idx` (`area_idarea` ASC),
  CONSTRAINT `fk_actividades_area1`
    FOREIGN KEY (`area_idarea`)
    REFERENCES `asscic`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `activo` BOOLEAN NOT NULL,
  `trabajador_idtrabajador` INT NOT NULL,
  PRIMARY KEY (`idadmin`, `trabajador_idtrabajador`),
  INDEX `fk_admin_trabajador1_idx` (`trabajador_idtrabajador` ASC),
  CONSTRAINT `fk_admin_trabajador1`
    FOREIGN KEY (`trabajador_idtrabajador`)
    REFERENCES `asscic`.`trabajador` (`idtrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`visita` (
  `idvisita` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(15) NULL,
  `org` VARCHAR(70) NULL,
  `tipo_visita` VARCHAR(10) NULL,
  `motivo` VARCHAR(45) NULL,
  `fecha` INT(11) NULL,
  `hora_llegada` INT(11) NULL,
  `hora_salida` INT(11) NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idvisita`, `persona_idpersona`),
  INDEX `fk_visita_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_visita_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`actividad_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`actividad_extra` (
  `idactividad_extra` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `voluntario_idvoluntario` INT NOT NULL,
  PRIMARY KEY (`idactividad_extra`, `voluntario_idvoluntario`),
  INDEX `fk_actividad_extra_voluntario1_idx` (`voluntario_idvoluntario` ASC),
  CONSTRAINT `fk_actividad_extra_voluntario1`
    FOREIGN KEY (`voluntario_idvoluntario`)
    REFERENCES `asscic`.`voluntario` (`idvoluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `asscic`.`institucion`
-- -----------------------------------------------------
START TRANSACTION;
USE `asscic`;
INSERT INTO `asscic`.`institucion` (`idinstitucion`, `nombre`) VALUES (DEFAULT, 'Universidad Nacional de Ingenierias');
INSERT INTO `asscic`.`institucion` (`idinstitucion`, `nombre`) VALUES (DEFAULT, 'Universidad de Managua');

COMMIT;


-- -----------------------------------------------------
-- Data for table `asscic`.`carrera`
-- -----------------------------------------------------
START TRANSACTION;
USE `asscic`;
INSERT INTO `asscic`.`carrera` (`idcarrera`, `nombre`) VALUES (DEFAULT, 'Ingenieria en ComputaciÃ³n');
INSERT INTO `asscic`.`carrera` (`idcarrera`, `nombre`) VALUES (DEFAULT, 'Ingenieria Industrial');
INSERT INTO `asscic`.`carrera` (`idcarrera`, `nombre`) VALUES (DEFAULT, 'Ingenieria en Sistemas');

COMMIT;

START TRANSACTION;
USE `asscic`;
INSERT INTO `asscic`.`area` (`idarea`, `nombre`,`descripcion`) VALUES (DEFAULT, 'Soporte TÃ©cnico','Area de reparaciÃ³n y mantenimiento');
INSERT INTO `asscic`.`area` (`idarea`, `nombre`,`descripcion`) VALUES (DEFAULT, 'C.I.','area de desarrollo y robÃ³tica');

COMMIT;

START TRANSACTION;
USE `asscic`;
INSERT INTO `asscic`.`persona` (`idpersona`,`nombre`,`apellido`,`cedula`,`direccion`,`telefono`,`correo`) VALUES (DEFAULT,'Jorge Antonio','Valverde Mejia','081-160299-1002H','Semaforos villa el progreso  andenes al lago y 90vrs. arriba','87925456','jorgeavalverdem@hotmail.com');

COMMIT;

START TRANSACTION;
USE `asscic`;
INSERT INTO `asscic`.`trabajador` (`idtrabajador`,`carnet`,`cargo`,`persona_idpersona`,`area_idarea`) VALUES (DEFAULT,'124556','Cargo 1',1,1);

COMMIT;

START TRANSACTION;
USE  `asscic`;
INSERT INTO `asscic`.`admin` (`idadmin`,`usuario`,`password`,`activo`,`trabajador_idtrabajador`) VALUES (DEFAULT,'jorge','1234',1,1);

COMMIT;

START TRANSACTION;
USE  `asscic`;
INSERT INTO `asscic`.`actividades` (`idactividades`,`nombre`,`area_idarea`) VALUES (DEFAULT,'ReparaciÃ³n',1);
INSERT INTO `asscic`.`actividades` (`idactividades`,`nombre`,`area_idarea`) VALUES (DEFAULT,'Mantenimiento',1);
INSERT INTO `asscic`.`actividades` (`idactividades`,`nombre`,`area_idarea`) VALUES (DEFAULT,'Desarrollo',2);
INSERT INTO `asscic`.`actividades` (`idactividades`,`nombre`,`area_idarea`) VALUES (DEFAULT,'RobÃ³tica',2);

COMMIT;
