-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 08:34:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asscic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asscic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asscic` DEFAULT CHARACTER SET utf8 ;
USE `asscic` ;

-- -----------------------------------------------------
-- Table `asscic`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(16) NOT NULL,
  `dirección` VARCHAR(150) NULL,
  `teléfono` INT(9) NOT NULL,
  `correo` VARCHAR(50) NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`Universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`Universidad` (
  `idUniversidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idUniversidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`voluntario` (
  `idvoluntario` INT NOT NULL AUTO_INCREMENT,
  `carnet` VARCHAR(45) NULL,
  `fecha_ingreso` INT(11) NOT NULL,
  `fecha_ultima` INT(11) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  `Universidad_idUniversidad` INT NOT NULL,
  `carrera_idcarrera` INT NOT NULL,
  PRIMARY KEY (`idvoluntario`, `persona_idpersona`, `Universidad_idUniversidad`, `carrera_idcarrera`),
  UNIQUE INDEX `carnet_UNIQUE` (`carnet` ASC),
  INDEX `fk_voluntario_persona1_idx` (`persona_idpersona` ASC),
  INDEX `fk_voluntario_Universidad1_idx` (`Universidad_idUniversidad` ASC),
  INDEX `fk_voluntario_carrera1_idx` (`carrera_idcarrera` ASC),
  CONSTRAINT `fk_voluntario_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntario_Universidad1`
    FOREIGN KEY (`Universidad_idUniversidad`)
    REFERENCES `asscic`.`Universidad` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntario_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `asscic`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`trabajador` (
  `idtrabajador` INT NOT NULL AUTO_INCREMENT,
  `carnet` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idtrabajador`, `persona_idpersona`),
  UNIQUE INDEX `carnet_UNIQUE` (`carnet` ASC),
  INDEX `fk_trabajador_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_trabajador_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`asistencia` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha` INT(11) NOT NULL,
  `hora_entrada` INT(11) NOT NULL,
  `hora_salida` INT(11) NOT NULL,
  `hora_acumulada` INT(11) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idasistencia`, `persona_idpersona`),
  INDEX `fk_asistencia_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_asistencia_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(100) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idarea`, `persona_idpersona`),
  INDEX `fk_area_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_area_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `asscic`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`actividades` (
  `idactividades` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(100) NULL,
  `area_idarea` INT NOT NULL,
  PRIMARY KEY (`idactividades`, `area_idarea`),
  INDEX `fk_actividades_area1_idx` (`area_idarea` ASC),
  CONSTRAINT `fk_actividades_area1`
    FOREIGN KEY (`area_idarea`)
    REFERENCES `asscic`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asscic`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asscic`.`visita` (
  `idvisita` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `cedula` VARCHAR(16) NULL,
  `placa` INT(11) NULL,
  `org` VARCHAR(70) NULL,
  `tipo_visita` VARCHAR(10) NULL,
  `motivo` VARCHAR(45) NULL,
  `fecha` INT(11) NULL,
  `hora_llegada` INT(11) NULL,
  `hora_salida` INT(11) NULL,
  PRIMARY KEY (`idvisita`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
